name: Go Benchmark Testing
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  deployments: write
  contents: write

jobs:
  benchmark:
    name: Benchmark
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Run benchmark
        run: |
          go test . -bench BenchmarkBuildFile -benchmem > output.txt
          go test . -bench Read -benchmem >> output.txt
          go test . -bench Write -benchmem >> output.txt
          go test . -bench AlphaField -benchmem >> output.txt
          go test . -bench NumericField -benchmem >> output.txt
          go test . -bench ParseNumField -benchmem >> output.txt
          go test . -bench ParseStringField -benchmem >> output.txt
          go test . -bench BenchmarkMergeFiles -benchmem >> output.txt
          go test . -bench BenchmarkCalculateCheckDigit -benchmem >> output.txt
          go test ./server/ -bench Benchmark -benchmem >> output.txt

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: My Project Go Benchmark
          tool: 'go'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-fetch-gh-pages: true
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '120%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@adamdecaf'
          # Update files on master branch
          gh-pages-branch: master
          benchmark-data-dir-path: docs/dev/bench/
